version: '3.3'
services:
  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

# Persisting data to this volume makes it survive cluster restarts
volumes:
  mongodb_data:
